[gcp_service_account]
type = "service_account"
project_id = "decisive-talon-344217"
private_key_id = "766965b7713e1ca6f89762b514d983fe098814b8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/HurmB3dFHLVH
0CPdFyMJToNu2DDitI3Y6gBt1HO/iFBLO5l6kVo2b6mncb15qKrcAHB0boTVqFX5
qEgG7wKAdWAo5vFYeuRWBDyUFe7DZynOXYeAEhTLit1Z/Vd3YikH3n1OPC+dxJ/c
TljZqkpiRbibk3h9c9s504ZKlPzlMI+mDy3/qYh8j/JiNtkwe/xp672IF0uItAiw
5aRVd2VbTtH+Q1u+j0Ow/98Xy53SpielE6dnxy2ILAzEnTk39i2gMoYBp8JMz3aP
ZGNQoYBdPYbgk9ZOmXh7QWZe2zgqFICKrZwe+QRFoIXcxWsLjNzVsowouu6s9udT
1rZj7gTJAgMBAAECggEAAx1R3qXIf8vT+HOf4f56h7BL3AaR5V/j3+EQWLnZmQlz
pYY3HhQ4UCLJtPzZhZ4GCsfHDV6vs3umywa/Bb3nYIiJJKF+1V5LUkuHYTJqTazk
tYQ4rRGeXSLKMKk8P6nN2V7608ePTxbhNAni0MlBpRBVzdM9Z2336J1V1ulOpb15
lvOFeus/XIKRb6lUvzdtDE07ZGCm2D3bo78tPfkQqlk+6FFZy0RX3GFGgNUoI6Ww
OMv5pDMJF9fgK8CWOiN+ls7srq33Kw1sG9ZTJkEVapQmtIuUtneDuVJGnIY0TbzW
DbMQW2iMtKWHFxohKfl2fA+4V+jvqXwAj+FZP4h9sQKBgQD5WvhU+qhmr7xR94FG
pClxNPPnJiZld532tyy0aUEXptENp8ZqvBwEYsWpS5645Mz8B18WjeCGYplrsdXo
6A9VDpVyCm1Ken4zGj65TrSUEfTjsUUq89SHFFcHDtLjy+N8d6x4I1Wsl0+shg9P
sBJaZ9g5klQhTdujHzh4p0SmuwKBgQDENrAnDmsDLTP/wzbpqvZvd4mmDoPIITeo
H2Y+RNPflVn9fbysyV5c2uYaciEn2jv1U9SUpQEwhi3znpT7SMcH9PdT0ijESBvF
jX4d4jqqN7tixzVwYHe2tvm6r7eXf3nvVOTXpSDrDLOrKlBo/s3Qr3tN4dcVqQPD
wRqdZ97ESwKBgH9YxEayFNsMmQLLgoxPPpMAVigQxb9ATb44Ym5o6sNngJCWxLCy
DST4RLZnVlJbF40HPrrIDojTRkNH+VUPXvUzk4NAa/yDfnwexTXiSjrsyMKYQBjl
mf66lo+WNIH+GNnyTHS2pwST6i7T8HHkHBtruXP9lVXE64ztXuvPkTINAoGBAJqs
OaQwG29/nLQLYShGGsm3w4xheMS0WrlvNxvzCcoAY9YN3kOe4YH1FNrYCQbvY8B6
euNKR2vG+kZHRk3oCu1cz/MFghlodmv+o+JOycwQ7uho/Nk/Ul94Udg2WFVWqfpe
Q58yjoZ7ls5hJs39vqS5EExOsUxj1ZHkkWRv0w2NAoGBANwAUADAc3lFr8H9GUWD
hkcS2viPZpUuDMr51AGWo1i+/uyIpMk3KEozuDHFOEuqah/2fSASVlD1OYg/OJ21
oTAv1P3MH84PTHWDxWTctKeQ4r4MDJBjmB+sB1xES55mskTh6asRFepYw6tQ9t4g
nUvkN9YatFEfXuz7OHY1aneO
-----END PRIVATE KEY-----"""
client_email = "labelling-linguistica@decisive-talon-344217.iam.gserviceaccount.com"
client_id = "100995710059295894820"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/labelling-linguistica%40decisive-talon-344217.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
